services:
  api:
    build: .
    container_name: api
    entrypoint:
      - sh
      - -c
      - |
        echo "⏳ Starting API server…";
        exec uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
  ollama:
    image: "ollama/ollama:latest"
    container_name: ollama
    entrypoint:
      - sh
      - -c
      - |
        exec ollama serve &
        sleep 5
        echo "⏳ Pulling llama3.2 model…"
        ollama pull llama3.2
        wait
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices: []
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: CMD-SHELL curl -f http://127.0.0.1:11434/api/tags || exit 1
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  ollama_data:
