services:
  api:
    build: .
    container_name: api_nollama
    entrypoint:
      - sh
      - -c
      - |
        echo "⏳ Starting API server…";
        exec uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"